### ISSUE TITLE
Fix properly the warnings at Arlas-server startup

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-server#428]
At ARLAS-server startup several warnings are thrown (Reference #419)
```
WARN  [2019-03-11 18:03:02,500] org.reflections.Reflections: could not get type for name org.zeroturnaround.javarebel.ClassEventListener from any class loader
! java.lang.ClassNotFoundException: org.zeroturnaround.javarebel.ClassEventListener
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 73 common frames omitted
``` 
The warnings are due to the upgrade of `dropwizard-swagger` to 1.2.x

This [link](https://stackoverflow.com/questions/49782606/dropwizard-swagger-with-dropwizard-1-3/53675582) explains the source of problem

This upgrade introduces BeanConfig.
"BeanConfig scanns all classes (not only the ones you set as resource packages) and tries to create class objects for them.

The "problem" is that there are plenty of classes in the resulting shaded jar that are using import statements of classes that are not provided/used by your (or alt least mine) dropwizard application."

**Comment by MohamedHamouGisaia** [comment]
This warning does not exist anymore after upgrade of `dropwizard-swagger` to 2.0.12-1. Closing.

@alainbodiguel @mbarbet
