### ISSUE TITLE
Incorrect error message on badly formatted `ARLAS_ELASTIC_NODES`

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-server#594]
**What happened**:

I passed `ARLAS_ELASTIC_NODES=https://my.elasticsearch:9300` to ARLAS-server, it resulted in following error:

```
io.arlas.server.exceptions.ArlasConfigurationException: Elastic search configuration missing in config file.
	at io.arlas.server.app.ArlasServerConfiguration.check(ArlasServerConfiguration.java:148)
	at io.arlas.server.app.ArlasServer.run(ArlasServer.java:123)
	at io.arlas.server.app.ArlasServer.run(ArlasServer.java:93)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.arlas.server.app.ArlasServer.main(ArlasServer.java:97)
```

**What you expected to happen**:

Problem comes from the fact that the `https://` prefix makes the parsing fail, so I was expecting an error message more in the like of:

```
Configuration entry `elastic-nodes` badly formatted.
```

**How to reproduce it (as minimally and precisely as possible)**:

Start ARLAS-server with `ARLAS_ELASTIC_NODES=https://my.elasticsearch:9300`

**Environment**:

ARLAS-server version: 12.7.1

**Comment by alainbodiguel** [comment]
The code has been changes since and this exception is no longer raised.
